config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :users, only: [:index]

  resources :movies, only: [:index, :create]

  resources :favorites, only: [:index, :create, :show, :destroy]

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :movie, uniqueness: { scope: :user }
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :favorited_users, class_name: "User", through: :favorites
  has_many :favorites

  validates :title, presence: true
  validates :year, presence: true
  validates :synopsis, presence: true
  validates_uniqueness_of :rotten_tomatoes_id

  def self.api_search(query)
    MoviesApi.movies_search(query)['movies']
  end
end

app/models/query.rb
class Query < ActiveRecord::Base
  validates :content, presence: true

  def self.remember_recent(query)
    self.create(content: query)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorite_movies, class_name: "Movie", through: :favorites
  has_many :favorites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def show
  @favorite = Favorite.find(params[:id])
end
def destroy
  @favorite = Favorite.find(params[:id])
  @favorite.destroy
  redirect_to users_path
  flash[:notice] = "You have removed a favorite."
end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @queries = Query.limit(10).order("created_at DESC")
    @movies = Movie.all
    if params[:search] && !params[:search].empty?
      @movies = Movie.api_search(params[:search])
      Query.remember_recent(params[:search])
    else
      flash[:notice] = "You performed an empty search"
    end
  end
  def create
    @movie_record = Movie.find_or_initialize_by(movie_params) do |movie|
      movie.title = params[:title]
      movie.year = params[:year]
      if params[:synopsis].empty?
        movie.synopsis = "NA"
      else
        movie.synopsis = params[:synopsis]
      end
      movie.rotten_tomatoes_id = params[:rotten_tomatoes_id]
    end
    @movie_record.save

    @favorite = Favorite.new(movie_id: @movie_record.id, user_id: current_user.id)
    if @favorite.save
      flash[:notice] = 'You successfully added a favorite movie!'
      redirect_to users_path
    else
      flash[:notice] = 'You already have that favorite.'
      @queries = Query.limit(10).order("created_at DESC")
      redirect_to :back

    end
  end

private

def movie_params
  params.permit(:rotten_tomatoes_id)
end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @queries = Query.limit(10).order("created_at DESC")
    @movies = Movie.all

    # if params[:search] && params[:search][:query]
    #   @movies = Movie.api_search(params[:search][:query])
    #   Query.remember_recent(params[:search][:query])
    # elsif params[:seach] && params[:search].empty?
    #   flash[:notice] = "You performed an empty search"
    # end

    @favorites = Favorite.where(user_id: current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @queries = Query.limit(10).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>ohmymovie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class='navbar-brand'>
          <%= link_to 'ohmymovie', root_path %>
          </div>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to("Signed in as #{current_user.email} (Sign out?)", destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to 'My Favorite Movies', users_path %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
  <% if flash.any? %>
    <% flash.each do |type, message|%>
      <div class='alert alert-info'><%= message %></div>
    <% end %>
  <% end %>
<%= yield %>
  </div>
</body>
</html>

app/views/movies/index.html.erb
<%= form_tag movies_path, method: :get do %>
  <p>
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Find Films", name: nil %>
  </p>
<% end %>

<h3>Recent Searches</h3>
<ul>
  <% @queries.each do |query| %>
    <li><%= link_to query.content, movies_path(search: query.content) %></li>
  <% end %>
</ul>

<% if @movies.empty? %>
  <h1>Not found</h1>
<% end %>


<% @movies.each do |movie| %>
  <div>
    <%= movie["title"] %>
    <%= movie["year"] %>
    <% if user_signed_in? %>
      <%= button_to 'Favorite', { controller: :movies, action: :create, title: movie["title"], year: movie["year"], synopsis: movie["synopsis"], rotten_tomatoes_id: movie["id"] }, method: :post %>
    <% end %>
    <% if !movie["synopsis"].empty? %>
      <%= movie["synopsis"] %>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= form_tag movies_path, method: :get do %>
  <p>
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Find Films", name: nil %>
  </p>
<% end %>

<h3>Recent Searches</h3>
<ul>
  <% @queries.each do |query| %>
    <li><%= link_to query.content, movies_path(search: query.content) %></li>
  <% end %>
</ul>

<h1>Favorites Page</h1>

<% @favorites.each do |favorite| %>
<div>
<%= favorite.movie.title %>
<%= favorite.movie.year %>
<%= favorite.movie.synopsis %>
<%= button_to "Delete", favorite_path(favorite.id), method: :delete %>
</div>
<% end %>

app/views/welcome/index.html.erb
<%= form_tag movies_path, method: :get do %>
  <p>
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Find Films", name: nil %>
  </p>
<% end %>

<h3>Recent Searches</h3>
<ul>
  <% @queries.each do |query| %>
    <li><%= link_to query.content, movies_path(search: query.content) %></li>
  <% end %>
</ul>